name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-v2-${{ matrix.project }}-${{ hashFiles('gradle.properties') }}-${{ hashFiles('gradle-plugins/**.kt*') }}-${{ hashFiles(format('{0}/**/*.kt*', matrix.project)) }}
          restore-keys: |
            gradle-cache-v2-${{ matrix.project }}-${{ hashFiles('gradle.properties') }}-${{ hashFiles('gradle-plugins/**.kt*') }}
            gradle-cache-v2-${{ matrix.project }}-${{ hashFiles('gradle.properties') }}
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check the project
        run: ./gradlew check